Kernel - Fix subfolder property when using mount manager
dokan-dev/dokany pull request #1053
Opened 2022-01-22 03:39 UTC by ATRiiX

Fixes #355 . 
Compared with opening the properties of windows local drive's sub-directories, I found the IOCTL_MOUNTDEV_QUERY_DEVICE_NAME return STATUS_INVALID_PARAMETER, while the dokan mirror drive's sub-dir return SUCCESS. However, it only take effect when the mountmanager option on, so I add a check for UseMountManager and IsVolumeOpen there.
The original IsVolumeOpen was not always work, and I found the FsContext can be NULL when open the properties, so I modify the IsVolumeOpen judgement.

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the existing documentation
- [x] My changes generate no new warnings
- [ ] I have updated the change log (Add/Change/Fix)
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- add IsVolumeOpen check and return STATUS_INVALID_PARAMETER in the IOCTL_MOUNTDEV_QUERY_DEVICE_NAME
- modify the IsVolumeOpen implementation, add check for FsContext != NULL
-

2022-01-22 03:53 UTC, Liryna commented
@ATRiiX Hi @ATRiiX,

Thanks for the PR!

Now that I read a little more the code, I believe the DiskDeviceControl should not include the MOUNTDEVCONTROLTYPE ioctl at all and have its own function that does the IsVolumeOpen check .
Like actually implement the switch case here with the two  functions and remove the IsVolumeOpen comment
https://github.com/dokan-dev/dokany/blob/3f7227cb7ba25c7caf78610daabd0e0376098745/sys/device.c#L739-L769

2022-01-22 10:00 UTC, ATRiiX commented
Hi @Liryna , thanks for the reply.
I have update the pr with your suggestions. Now add IsVolumeOpen check when the code MOUNTDEVCONTROLTYPE, and test it can also fix the properties issue. Please take some time to review the pr.

2022-01-22 15:01 UTC, Liryna requested changes

2022-01-22 15:01 UTC, Liryna commented on sys/device.c
> +                       RequestContext->IrpSp->FileObject)) {
```
if (!IsVolumeOpen(...){
   status = STATUS_INVALID_PARAMETER;
   break;
}
status = DiskDeviceControlWithLock(....
```

2022-01-22 15:36 UTC, Liryna commented
Thanks @ATRiiX for the quick change! I added some small comments and I believe we are good to merge it 😎

2022-01-22 18:10 UTC, ATRiiX commented on sys/device.c
> +           FileObject->FsContext != &Vcb->VolumeFileHeader);
I added the log of FsContext on win11 and didn't see a case where it was equal to null. I think I've misremembered it. :)
So just keep the original judgment condition here.

2022-01-22 18:13 UTC, ATRiiX commented on sys/device.c
> +                       RequestContext->IrpSp->FileObject)) {
Thanks, I have updated it.

2022-01-23 21:55 UTC, merged

2022-01-23 21:56 UTC, Liryna commented
Thanks again for your contribution @ATRiiX 🏆 very appreciated!